require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
require 'xcodeproj'

# Xcode 26 uses object version 70 - patch xcodeproj to recognize it
module Xcodeproj
  class Project
    DEFAULT_OBJECT_VERSION = 70

    # Override the initializer if needed
    module FixXcode26
      def object_version_from_compatible_with(version)
        return 70 if version == 70
        super
      end
    end
  end

  module Constants
    # Add the mapping for Xcode 26 (object version 70)
    COMPATIBILITY_VERSION_BY_OBJECT_VERSION = {} unless defined?(COMPATIBILITY_VERSION_BY_OBJECT_VERSION)
    COMPATIBILITY_VERSION_BY_OBJECT_VERSION[70] = 'Xcode 16.0'
    
    OBJECT_VERSION_TO_HUMAN = {} unless defined?(OBJECT_VERSION_TO_HUMAN)
    OBJECT_VERSION_TO_HUMAN[70] = 'Xcode 16.0'

    LAST_KNOWN_OBJECT_VERSION = 70
  end
end

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  
  # Firebase SDK
  # pod 'FirebaseCore'
  # pod 'FirebaseAuth'
  # pod 'FirebaseFirestore'
  # pod 'FirebaseAnalytics'
  # pod 'FirebaseVertexAI'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
