require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
require 'xcodeproj'

# Xcode 16 uses object version 70 which older xcodeproj doesn't map; force a known compatible version.
Xcodeproj::Project::DEFAULT_OBJECT_VERSION = 60

module Xcodeproj
  module Constants
    OBJECT_VERSION_TO_HUMAN = {} unless defined?(OBJECT_VERSION_TO_HUMAN)
    OBJECT_VERSION_TO_HUMAN[70] = 'Xcode 16.0'
  end
end

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
